### ISSUE TITLE
Clicking on Lists times out with two different bookwrym servers

### ISSUE THREAD

**Issue by holliebutler** [bookwyrm-social/bookwyrm#2117]
I'm new to the Fediverse (and new to GitHub, so apologies in advance for any mistakes). I discovered Bookwyrm a couple of weeks ago. I'm running into a problem with two different bookwyrm instances. My first account was with wyrms.de, and when that seemed broken, I got another account on bookrastinating.com. When the same problem happened there, I contacted the admin for wyrms.de, who suggested I make a ticket here. 

With both servers, whenever I click on "Lists" at the top, it goes to a page of Lists. Great. 
But then when I click on any of the lists, any list at all, doesn't matter which one: the link times out. I can't reach any of the lists.  

I do the following: 
1. Go to Wyrms.de or Bookrastinating and log myself in.
2. Go to the top of the page and click on Lists. 
3. On the Lists page, click on any list title link. 

This happens on:
my iMac (12.3.1) using either Safari or Firefox or Chrome
my iPhone Pro Max 13 (Safari)
my iPad mini or regular iPad (Safari)

It happens when I'm home, and when I'm using one of my devices away from home. 

![502_Bad_Gateway](https://user-images.githubusercontent.com/105510219/169164878-a0ce0fc2-3648-41a5-81b5-11e6b6cf8738.jpg)

![502_Bad_Gateway](https://user-images.githubusercontent.com/105510219/169164902-04124969-357c-40a7-9a1f-7b6314b861b7.jpg)

**Comment by mouse-reeve** [comment]
I suspect that I wrote some kind of terribly inefficient query that's causing this. Thank so much for reporting!

**Comment by mouse-reeve** [comment]
I've deployed a potential fix for this on bookwyrm.social, but because I haven't been able to replicate the issue, I want to make sure you are seeing an improvement before I consider this ready to close. When wyrms.de or bookrasting upgrade to version 0.4.0, can you let me know if lists start working again?

**Comment by holliebutler** [comment]
> When wyrms.de or bookrasting upgrade to version 0.4.0, can you let me know if lists start working again?

I'd be happy to! I created a to-do for myself to check daily to see what version they're on. Looks like right now they're both on 0.3.4.

**Comment by EloiR** [comment]
It still happens with bookwyrm.social (0.4.0)

**Comment by holliebutler** [comment]
It's still happening for me with wyrms.de as well. 

I also tried bookrastinating.com but couldn't load the site at all.

**Comment by mouse-reeve** [comment]
Okay, that's too bad but thank you for letting me know. I'll take another look.

**Comment by holliebutler** [comment]
Unfortunately, wyrms.de is 0.4.3 and I still get the same bad gateway timeout when I try to access a list (tries on multiple lists). 

Bookrastinating.com still 0.4.2 and the problem remains there as well.

**Comment by mouse-reeve** [comment]
For lists that don't load, are you able to see them when you're logged out?

**Comment by holliebutler** [comment]
> For lists that don't load, are you able to see them when you're logged out?

I don't seem to have access to lists when I'm logged out (looking at wyrms.de). 

I'm able to click on a few books featured on the home page, and I clicked through those hoping maybe I'd see a link like, "Appears on this list," and then I could click on a list link that way. But none of the books I clicked through had those.

When I'm logged in, the link for lists is: https://www.wyrms.de/list

When I'm logged out, and I go to that URL, the page says "Lists" but is empty of content so I can't test it.

**Comment by mouse-reeve** [comment]
Oh! That's a separate bug. Can you copy the url of a list that doesn't load and go directly to it while logged out (or in a private browsing window)? For example, https://www.wyrms.de/list/23/s/mycological-lit, from the original report

**Comment by holliebutler** [comment]
> Oh! That's a separate bug. Can you copy the url of a list that doesn't load and go directly to it while logged out (or in a private browsing window)? For example, https://www.wyrms.de/list/23/s/mycological-lit, from the original report

Sure! And yes! When I click on that link, it goes straight to the list, no waiting. :) I'm currently logged out.

If I log in, that list link times out.

**Comment by holliebutler** [comment]
This is still broken for me. Today I was able to get an account on bookwyrm.social, and all three sites (bookrastinating.some, wyrms.de, bookwyrm.social) go to "Bad Gateway" when I try to look at lists.

**Comment by SyndicatedPillbug** [comment]
Oh, whoops, I just made a bug report for this because I somehow missed seeing this thread. I'm getting the exact issue across two different servers as well.

**Comment by mouse-reeve** [comment]
Can someone re-open this if it's still an issue? We've made a number of performance improvements in the intervening time and I'm hoping this is now not a problem 🤞
